### ISSUE TITLE
./lib/lib set as mp3ParserLib on globals but referenced as lib in global import statements

### ISSUE THREAD

**Issue by mattmarcum** [biril/mp3-parser#3]
I'm trying to use this in an ember-cli project via the global method.  I couldn't get mp3-parser to load until I realized that the `lib/lib.js` module was undefined in all the consuming modules.  It looks like the culprit are these lines:

https://github.com/biril/mp3-parser/blob/master/lib/id3v2.js#L34
https://github.com/biril/mp3-parser/blob/master/lib/xing.js#L34
https://github.com/biril/mp3-parser/blob/master/main.js#L34

Once I changed these to reference `globalObject. mp3Parserlib` it worked.  That name is defined here:
https://github.com/biril/mp3-parser/blob/master/lib/lib.js#L26

**Comment by biril** [comment]
That's absolutely right - thanks a lot :+1: 

Fixed in [0.2.6](https://github.com/biril/mp3-parser/releases/tag/0.2.6).
