### ISSUE TITLE
uncaught range error leads to crash with some mp3s

### ISSUE THREAD

**Issue by conceptualspace** [biril/mp3-parser#4]
mp3-parser\lib\lib.js:223 Uncaught RangeError: Invalid typed array length

 return String.fromCharCode.apply(null, new Uint16Array(buffer, offset, length / 2));
                                                   ^
 RangeError: Invalid typed array length
    at new Uint16Array (native)
    at Object.lib.readStr.ucs (node_modules\mp3-parser\lib\lib.js:223:52)
    at readFrameContentIpls (node_modules\mp3-parser\lib\id3v2.js:331:53)
    at Object.mp3Id3v2Parser.readId3v2TagFrame (node_modules\mp3-parser\lib\id3v2.js:559:28)
    at Object.mp3Id3v2Parser.readId3v2Tag (node_modules\mp3-parser\lib\id3v2.js:638:36)
    at Object.mp3Parser.readId3v2Tag (node_modules\mp3-parser\main.js:113:28)

**Comment by conceptualspace** [comment]
also seeing

"Uncaught RangeError: Offset is outside the bounds of the DataView",
node_modules\mp3-parser\lib\lib.js:135
            if (seq[i] !== view.getUint8(offset + i)) { return false; }
                                ^

RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (native)
    at FileReader.reader.onload

**Comment by conceptualspace** [comment]
it's occurring infrequently in a large batch job, where i'm just skipping the track if it throws the error. but if its helpful i can attach the problematic file

**Comment by biril** [comment]
Yes please do and I'll take a look. Thank you 👍

**Comment by biril** [comment]
@conceptualspace [Version 0.3.0](https://github.com/biril/mp3-parser/releases/tag/0.3.0) of the library [fixes a defect in IPLS frame parsing](https://github.com/biril/mp3-parser/commit/36da106b33b65a56f21fe6e315bdc7552cafe0dd), which is quite possible the source of the errors you were seeing. You can give it a go if this is still useful to you 😄 .

I'm going to go ahead and close this as I believe it's resolved. Thanks for the original report.
